### ISSUE TITLE
'Api' object has no attribute 'async_client'

### ISSUE THREAD

**Issue by 3ayazaya** [KrazyKirby99999/simple-matrix-bot-lib#101]
**Trouble with launch bot**
After installing the necessary packages and this library, the bot cannot start.

**Launched script**
```python"""
Example Usage:

random_user
      !echo something

echo_bot
      something
"""
import simplematrixbotlib as botlib

creds = botlib.Creds(homeserver="https://matrix.org", username="my_username", password="my_pass")
bot = botlib.Bot(creds)
PREFIX = '!'


@bot.listener.on_message_event
async def echo(room, message):
    match = botlib.MessageMatch(room, message, bot, PREFIX)

    if match.is_not_from_this_bot() and match.prefix() and match.command(
            "echo"):

        await bot.api.send_text_message(room.room_id,
                                        " ".join(arg for arg in match.args()))


bot.run()
```
**Error**
<img width="884" alt="Снимок экрана 2021-12-19 в 16 57 38" src="https://user-images.githubusercontent.com/22868859/146677713-5f07d011-5649-48b9-b987-d868c469c068.png">

**Comment by KrazyKirby99999** [comment]
Which version is this with? 2.5.0?

**Comment by 3ayazaya** [comment]
> Which version is this with? 2.5.0?

Last in your repo

**Comment by KrazyKirby99999** [comment]
@3ayazaya  Version 2.5.1 should fix this. Can you update and check if this issue still occurs?

**Comment by 3ayazaya** [comment]
> @3ayazaya Version 2.5.1 should fix this. Can you update and check if this issue still occurs?

Okay :)
