### ISSUE TITLE
add simple to use listener for reactions

### ISSUE THREAD

**Issue by HarHarLinks** [KrazyKirby99999/simple-matrix-bot-lib#122]
**Is your feature request related to a problem? Please describe.**
https://matrix.to/#/!yRgNdNVvyeIgpYRBit:matrix.org/$FZSIFCi2Fv7EWef_P5ykK-TaRBjeJF9dCuDEa_YtHvc?via=matrix.org

**Describe the solution you'd like**
`@bot.listener.reaction` decorator

**Describe alternatives you've considered**
`@bot.listener.on_custom_event(nio.Reaction)` or whatever the proper class is

**Comment by KrazyKirby99999** [comment]
Please close if this is resolved by using version `2.6.0`.

**Comment by KrazyKirby99999** [comment]
Closed anyway
