### ISSUE TITLE
`git tag` releases

### ISSUE THREAD

**Issue by HarHarLinks** [KrazyKirby99999/simple-matrix-bot-lib#125]
Please tag your releases in git.

I think it would be good to tag commits that are released, to draw references from package versions to git commits without having to search the commit messages. Also it would be a good way to have release/patch notes/changelog.
https://github.com/KrazyKirby99999/simple-matrix-bot-lib/releases

**Comment by KrazyKirby99999** [comment]
I have tagged each "bump version" commit with the corresponding version. Currently searching for a github action or other method to conveniently generate a changelog.

**Comment by HarHarLinks** [comment]
While you can generate a changelog simply from the commits from tag to tag, some would argue that release notes should rather be more human readable and point out only most significant changes. Your TWIM posts could at least partially be these release announcements.

The former list can be viewed by GitHub using the compare function such as https://github.com/KrazyKirby99999/simple-matrix-bot-lib/compare/v2.5.1...v2.6.0. This is advertised in the "Releases" UI once you make a release, see for example: https://github.com/HarHarLinks/matrix-webhook-receiver/releases
![image](https://user-images.githubusercontent.com/2803622/149846210-b6a6528f-28ff-4a73-b1e3-703eb6e5ac6e.png)

**Comment by KrazyKirby99999** [comment]
I added a changelog following this to the changelog branch:
```markdown
## vX.Y.Z
### YYYY-MM-DD HASHHASH
### Notes:
None
### Additions:
- None
### Modifications:
- None
### Removals:
- None
### Deprecations:
- None
```

**Comment by HarHarLinks** [comment]
are you going to use releases as well? https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases

**Comment by KrazyKirby99999** [comment]
I do plan on using releases as well.
