### ISSUE TITLE
No message event

### ISSUE THREAD

**Issue by Ryu1845** [KrazyKirby99999/simple-matrix-bot-lib#126]
**Describe the bug**
Function decorated by `@bot.listener.on_message_event` are not triggered when message is sent.

**To Reproduce**
The echo example doesn't work.

**Expected behavior**
I expected message events to be handled

**Screenshots**
N/a

**Desktop (please complete the following information):**
 - Arch Linux
 - Python 3.10.1 (also tested on 3.9.9)
 - Package Version 2.6.0

**Additional context**
I am working on a bot and while it was working a few weeks ago. I can't create a new instance of it. It looks like it doesn't detect the messages being sent.

**Comment by KrazyKirby99999** [comment]
Are the messages being sent in an encrypted room?

**Comment by Ryu1845** [comment]
Let me check actually, I'm dming it so that might be the problem

**Comment by Ryu1845** [comment]
Well really sorry for your loss of time it was really that…

**Comment by KrazyKirby99999** [comment]
No problem at all. Encryption support is planned in the future.
