### ISSUE TITLE
Request for clientpoke support

### ISSUE THREAD

**Issue by Zedjones** [KrazyKirby99999/simple-matrix-bot-lib#38]
I'd like to add the ability to poke users from a Matrix bot, but there doesn't seem to be any way to do so with this library currently (unless I'm missing something).

I can probably get around this by using the private `_send` function, but proper support would be great.

Thanks for the awesome work on this! It's definitely an improvement over the library I was using before.

**Comment by Zedjones** [comment]
This is the wrong library, apologies. I had too many tabs open...

**Comment by KrazyKirby99999** [comment]
No problem, that is completely understandable anyway.
