### ISSUE TITLE
Login with token such as when using SSO

### ISSUE THREAD

**Issue by ser** [KrazyKirby99999/simple-matrix-bot-lib#52]
It would be useful to allow logging with externally generated Access Token, for example in a situation when your home server has SSO login only.

**Comment by KrazyKirby99999** [comment]
Is this what you mean?
```python
creds = botlib.Creds(
    homeserver="https://example.org",
    access_token="ACCESSTOKENHERE"
    )
```

**Comment by ser** [comment]
yes it is indeed :) sorry i could not find it anywhere in docs, i read them several times :)

thanks :)

**Comment by KrazyKirby99999** [comment]
This is not supported yet, I was only asking if that is what you meant.

**Comment by ser** [comment]
Ahh, OK!

BTW, is room presence planned - when someone enters/leaves a specified room? ```bot.add_presence_listener()```

**Comment by KrazyKirby99999** [comment]
In the upcoming version 2, it is possible to add a listener for any event, so a presence listener is possible.

**Comment by KrazyKirby99999** [comment]
I intend to add support for both of the following syntax in version 2.
```
creds = botlib.Creds(
    homeserver="https://example.org",
    username="username"
    access_token="ACCESSTOKENHERE"
    )
```
    
```
creds = botlib.Creds(
    homeserver="https://example.org",
    username="username"
    password="password"
    )
```

**Comment by ser** [comment]
Amazing, be waiting in the wings for version 2, I'm ready to test. 

These two functionalities,  bot.add_presence_listener() and bot.add_message_listener() build a perfect simple bot which can be used in 95% of cases.

Thanks again :)

**Comment by KrazyKirby99999** [comment]
I want to let you know that the new syntax for listeners will use decorators instead of an ordinary method, so it will be partially incompatible, although it should be easy to adapt to.

**Comment by KrazyKirby99999** [comment]
It has come to my attention that "access_token" is a separate concept from the token used to login, so this token will be referred to as "login_token" instead. The username is also unnecessary when using login tokens. The corrected syntax would be as below:
```python
creds = botlib.Creds(
    homeserver="https://example.org",
    login_token="LOGINTOKENHERE"
    )
```

**Comment by KrazyKirby99999** [comment]
The feature should now be complete and ready to add to the v2 branch. You can check the pull request here #53 , and the documentation for it here https://simple-matrix-bot-lib.readthedocs.io/en/login-rework/manual.html#creating-an-instance-of-the-creds-class. Please let me know if you find any issues with it, otherwise I will merge it into the v2 branch tomorrow.

**Comment by ser** [comment]
Hi Krazy - I have already moved my development to v2 branch - so I will be able to test it after you submit it into v2.

**Comment by ser** [comment]
BTW, ```@bot.listener.on_custom_event(nio.RoomMemberEvent)``` works pefectly, it's amazing how effective and simple your library is 💯

**Comment by KrazyKirby99999** [comment]
I will perform the merge then, and glad to hear that :)

**Comment by ser** [comment]
quick question: what is the best way to run nio api commands, for example from inside  ```@bot.listener.on_message_event``` i want to get all room members, https://matrix-nio.readthedocs.io/en/latest/nio.html#nio.Api.joined_members

**Comment by KrazyKirby99999** [comment]
Importing from nio, then using it as specified by the nio docs.
```
import nio
nio.api.Api.joined_rooms(access_token)
```
I am not able to make sure that this works right now, but I will check tomorrow.

It is probably best if you ask further questions via the Matrix Room [#simplematrixbotlib:matrix.org](https://matrix.to/#/#simplematrixbotlib:matrix.org).

**Comment by ser** [comment]
I would love to join, but it says i am not invited :(
My matrix handle is @ser:tldp.net

**Comment by KrazyKirby99999** [comment]
I corrected the join rules and invited you to be sure, my apologies.
