### ISSUE TITLE
hardcoded matrix.org when logging in with access_token

### ISSUE THREAD

**Issue by HarHarLinks** [KrazyKirby99999/simple-matrix-bot-lib#74]
https://github.com/KrazyKirby99999/simple-matrix-bot-lib/blob/96b120e9ea7425a117fb08918a2993ec6fb86e41/simplematrixbotlib/api.py#L58

should be

```python
async with session.get(f'{self.creds.homeserver}/_matrix/client/r0/account/whoami?access_token={self.creds.access_token}') as response:
```

or so

**Comment by KrazyKirby99999** [comment]
Thank you for bringing this issue to my attention, I will fix this as soon as possible.
