### ISSUE TITLE
match.py: IndexError: list index out of range

### ISSUE THREAD

**Issue by HarHarLinks** [KrazyKirby99999/simple-matrix-bot-lib#86]
https://github.com/KrazyKirby99999/simple-matrix-bot-lib/blob/aaa71d41603f8f8d02dbf4f88f7ca272db4d2af9/simplematrixbotlib/match.py#L110-L113

https://github.com/KrazyKirby99999/simple-matrix-bot-lib/blob/aaa71d41603f8f8d02dbf4f88f7ca272db4d2af9/simplematrixbotlib/match.py#L135

These are candidates for IndexError: list index out of range

The first 2 need to be looked at, the second would be fixed in #81

**Comment by KrazyKirby99999** [comment]
When does this error occur?

**Comment by HarHarLinks** [comment]
when there are not arguments/at most 1 argument ("command")

**Comment by KrazyKirby99999** [comment]
I am unable to reproduce this. Can you provide an example?

**Comment by HarHarLinks** [comment]
- the `body_without_prefix.split()[0]` is actually caught in advance by `if not body_without_prefix:`
- `self.event.body.split()[1:]` does slicing magic to not error
